### ISSUE TITLE
It looks not loading app.css

### ISSUE THREAD

**Issue by lethe2211** [monaca-templates/onsenui-v2-angular2-minimum#6]
Hi, I'm using Monaca with Angular2+ and this template as well.
Thank you very much.

https://github.com/monaca-templates/onsenui-v2-angular2-minimum/blob/6f85977a6f2ce37e6653545b5967103335bda4c8/src/app/app.ts#L8

Regarding this line, is it supposed to read `src/app/app.css` as a CSS file, right?
If so, it looks not reading the file properly.

Angular does not read it as a relative file path but just a string `./app.css`, as far as I checked.

Could you confirm it?

**Comment by emccorson** [comment]
Thank you for your report, and sorry for the delay in replying.

This problem was fixed in #7 and merged so the CSS should be working now.

**Comment by lethe2211** [comment]
Hi, @emccorson 

Thank you very much for your fixing.
I confirmed now CSS is working!
